# Generated by Django 5.0.11 on 2025-01-23 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('CP', 'Completed'), ('IP', 'In Progress')], default='IP', max_length=2)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published'],
                'indexes': [models.Index(fields=['-published', 'title'], name='projects_pr_publish_f0fb3c_idx')],
            },
        ),
    ]
