# Generated by Django 5.0.11 on 2025-06-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='../media/blogs/%Y/%m/%d/'),
        ),
    ]
