# Generated by Django 5.0.11 on 2025-06-12 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_options_blog_published_alter_blog_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='Post',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blogs_post_publish_18efa0_idx',
            old_name='blogs_blog_publish_bc447a_idx',
        ),
    ]
