# Generated by Django 5.0.11 on 2025-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
