# Generated by Django 5.0.11 on 2025-02-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-school'],
                'indexes': [models.Index(fields=['-school'], name='about_educa_school_f29391_idx')],
            },
        ),
    ]
