# Generated by Django 5.0.11 on 2025-02-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('achievement', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveIndex(
            model_name='education',
            name='about_educa_school_f29391_idx',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='end_year',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_year',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['-start_date'], name='about_educa_start_d_36f5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['-start_date'], name='about_exper_start_d_49b316_idx'),
        ),
    ]
